### ISSUE TITLE
Loop server regtest documentation is not up to date

### ISSUE THREAD

**Issue by Jossec101** [lightninglabs/loop#549]
Hey,

I couldn't make loopserver work without adding a bitcoind node, but this aspect is not stated on the [documentation](https://github.com/lightninglabs/loop/tree/master/regtest) 

Besides, the examples use old version of LND.

Bonus: Here below you will find some guidelines on how to set up a regtest loop environment with a [Polar Lightning Network](https://lightningpolar.com/). Example polar network file: [regtest.polar.zip](https://github.com/lightninglabs/loop/files/10580893/regtest.polar.zip)

Steps: 
1. Set up polar lightning with the file above, also extract this file to a regtest.polar dir
2. Fix loopserver docker images to support bind mounted lnd datadir (from the extracted dir above)
```Dockefile
FROM lightninglabs/loopserver:v0.9.94-beta

COPY regtest.polar/volumes/lnd/alice /root/.lnd

USER root

RUN chmod -R 777 /root/.lnd
RUN chown -R loopserver:loopserver /root/.lnd

USER loopserver
```
3. Launch a loopserver and a loopd with the following docker-compose.yml
````yaml
version: '3'
services:
  loopserver:
    hostname: loopserver
    ports:
      - "11009:11009"
    extra_hosts:
      - "alice:host-gateway"
    #image: lightninglabs/loopserver:v0.9.77-beta
    build:
      context: .
      dockerfile: Dockerfile.loopserver
    platform: linux/amd64
    restart: unless-stopped
    networks:
      - regtest
    command:
      - "daemon"
      - "--maxamt=5000000"
      - "--lnd.host=alice:10001"
      - "--lnd.macaroondir=/home/loopserver/.lnd/data/chain/bitcoin/regtest"
      - "--lnd.tlspath=/home/loopserver/.lnd/tls.cert"
      - "--bitcoin.host=alice:18443"
      - "--bitcoin.user=polaruser"
      - "--bitcoin.password=polaruser"
      - "--bitcoin.httppostmode"
    volumes:
      - ./regtest.polar/volumes/lnd/alice:/home/loopserver/.lnd

  # loopd:
  #   image: loopd
  #   extra_hosts:
  #     - "carol:host-gateway"
  #   build:
  #     context: ./loop
  #     dockerfile: Dockerfile
  #   restart: unless-stopped
  #   networks:
  #     - regtest
  #   ports:
  #     - "11010:11010"
  #     - "8088:8081"
  #   volumes:
  #     - "./regtest.polar/volumes/lnd/carol:/root/.lnd"
  #     - "./loop:/root/.loop"
  #   command:
  #     - "loopd"
  #     - "--network=regtest"
  #     - "--debuglevel=debug"
  #     - "--server.host=loopserver:11009"
  #     - "--server.notls"
  #     - "--lnd.host=carol:10003"
  #     - "--lnd.macaroonpath=/root/.lnd/data/chain/bitcoin/regtest/admin.macaroon"
  #     - "--lnd.tlspath=/root/.lnd/tls.cert"

networks:
  regtest:
````
